task_app/urls.py
from django.urls import path
from task_app import views

urlpatterns = [
    path('', views.TaskList.as_view(), name='task_list'),
    path('task/<int:pk>/', views.TaskDetail.as_view(), name='task_detail'),
    path('task/<int:pk>/edit', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/create/', views.TaskCreate.as_view(), name='task-create'),  # Add this line for creating a new task
]

app_name = 'task_app'

task_progect/urls.py
from django.contrib import admin
from django.urls import path, include
from task_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_app.urls')),

]

task_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class State(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return str(self.name)

class Preoretis(models.Model):
    name = models.CharField(max_length=100)
    value = models.IntegerField()

    def __str__(self) -> str:
        return self.name + " - " + str(self.value)

class Task(models.Model):
    task_name = models.CharField(max_length=100)
    description = models.TextField()
    status = models.ForeignKey(State, on_delete=models.DO_NOTHING)
    preorety = models.ForeignKey(Preoretis, on_delete=models.DO_NOTHING)
    date_start = models.DateTimeField(blank=True, null=True)
    date_finished = models.DateTimeField(blank=True, null=True)

    creator = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL) #who created the task

    def __str__(self):
        return f"{self.task_name} ({self.status})"
    

task_app/forms.py
from django import forms
from task_app.models import Task, State
from django.contrib.admin import widgets  
from django.contrib.admin.widgets import AdminDateWidget

class TaskForm(forms.ModelForm):
    date_start = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    date_finished = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = Task
        fields = ['task_name', 'description', 'status', 'preorety']
 
class FilterTaskForm(forms.Form):
    print(list(State.objects.all()))
    result = []
    for  i in State.objects.all():
       result.append((i.name, i.name))
    
    status = forms.ChoiceField(choices=result, required=False, label='Статус')

task_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse
from .models import *
from task_app.forms import TaskForm, FilterTaskForm
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from django.shortcuts import get_object_or_404

class TaskList(ListView):
    model = Task
    template_name = 'task_app/tasklist.html'
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = FilterTaskForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        status = self.request.GET.get("status", 'all')
        if status != 'all':
            try:
                state = get_object_or_404(State, name=status)
                queryset = queryset.filter(status=state)
            except State.DoesNotExist:
                queryset = Task.objects.none()  # Empty queryset
        return queryset

class TaskDetail(DetailView):
    model = Task
    template_name = 'task_app/task_detail.html'
    context_object_name = 'task'

class TaskCreate(LoginRequiredMixin, CreateView):
    
    model = Task
    template_name = 'task_app/task_form.html'
    
    form_class = TaskForm
    success_url = '/'
    def form_valid(self, form):
        form.instance.date_start = form.cleaned_data['date_start']
        form.instance.date_finished = form.cleaned_data['date_finished']
        return super().form_valid(form)

class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "task_app/edit_task.html"
    context_object_name = "task"
    # fields = ['title', 'description']  # a subset of all fields
    # readonly_fields = ['date_modified']  # a subset of the `fields` tuple
    # can also specify form classes here if needed:
    form_class = TaskForm
    success_url = '/'
    def form_valid(self, form):
        form.instance.date_start = form.cleaned_data['date_start']
        form.instance.date_finished = form.cleaned_data['date_finished']
        return super().form_valid(form)

templates/task_app/add_task.html
{% extends "task_app/base.html" %}
{% block content %}
    <form method="post" class="add-task-form">
        <h1>Create Task</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

templates/task_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block connect_styles %}
    {% endblock connect_styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <title>Document</title>
</head>
<body>
    <header>      
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Trellogika</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">About project</a>
                  </li>
                  <li class="nav-item">
                    <a href="/task/create">Create task</a>
                  </li>
                </ul>
                <span class="navbar-text">
                  <a href="">Sign in</a>
                  <a href="">Sign up</a>
                </span>
              </div>
            </div>
          </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>

    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/task_app/edit_task.html
{% extends "task_app/base.html" %}
{% load static %}

{% block connect_styles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}
    <form method="post" class="add-task-form">
        <h1>Update Task</h1>
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit">Submit</button>
        <a href="/">back to list</a>

    </form>

{% endblock content %}

templates/task_app/task_detail.html
{% extends "task_app/base.html" %}
{% load static %}
{% block connect_styles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}
    <section class="task-details">

        <h1>{{ task.task_name }}</h1>
        <h3>{{ task.description }}</h3>
        <hr>
        <h2> Термін виконання </h2>
        <p>з {{ task.date_start }}</p>
        <p>до {{ task.date_finished }}</p>
        <a href="/">back to list</a>
        <a href="{% url 'task_app:task_update' task.pk %}">edit the task</a>
    </section>
{% endblock content %}

templates/task_app/task_form.html
{% extends "task_app/base.html" %}
{% load static %}

{% block connect_styles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}
    <form method="post" class="add-task-form">
        <h1>Create Task</h1>
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="/">back to list</a>

    </form>

{% endblock content %}

templates/task_app/tasklist.html
{% extends "task_app/base.html" %}
{% load static %}

{% block connect_styles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}
{% block content %}
    <div>
        <section class="filter-panel">
                <form method="get">
                    <h1>Search Tasks</h1>
                    {{ form.status.label_tag }}
                    <p>{{ form.status }}</p>
                    <input type="submit" class="filter-set-btn">
                </form>
        </section>

        <section>
                
            {% for task in tasks %}

                <section class="task">

                    <h1>{{ task.task_name }}</h1>
                    <h4>{{ task.description }}</h4>
                    <div><a href="{% url 'task_app:task_detail' task.pk %}">See more details...</a></div>
                    
                </section>
            {% endfor %}
            
        </section>
    </div>
    
    
{% endblock content %}